# -*- coding: utf-8 -*-
"""AnalisisNetflix2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GTLHqnCL_5PRWpBOtjLdq7BVb3JBslI4

# ANALISIS DE CONSUMO DE NETFLIX CON PYTHON

## 1. IMPORTACION Y CARGA DE DATOS
"""

from google.colab import files
datos = files.upload()

import io
import pandas as pd

df = pd.read_csv(io.BytesIO(datos['NetflixViewingHistory.csv']))

"""## 2. ANALISIS EXPLORATORIO"""

df.shape

df.info()

df.head(50)

"""Vemos que parece que existe un patrón en el que diferentes partes se se separan mediante dos puntos. Vamos a contar en cuantas partes distintas se seperan nuestros contenidos"""

separacion_lista = df.Title.str.split(pat = ':', expand=False).to_frame()
separacion_lista

separacion_lista['num_partes'] = separacion_lista.Title.apply(len)
separacion_lista

separacion_lista.num_partes.value_counts()

"""Vamos a analizar los títulos por número de partes a ver si hay algún patrón."""

separacion_lista.loc[separacion_lista.num_partes == 1].head(10)

separacion_lista.loc[separacion_lista.num_partes == 2].head(10)

separacion_lista.loc[separacion_lista.num_partes == 3].head(10)

separacion_lista.loc[separacion_lista.num_partes == 4].head(10)

separacion_lista.loc[separacion_lista.num_partes == 5].head(10)

"""## 3. CREACIÓN DE VARIABLES

Nuestro dataset original tiene muy pocas variables, pero con un poco de trabajo podemos generar nuevas variables. Este proceso se llama "feature extraction".

### 3.1 VARIABLES DERIVADAS DEL TÍTULO
"""

import numpy as np

separacion_lista['tipo'] = np.where(separacion_lista.num_partes <3, 'pelicula', 'serie')
separacion_lista

df = pd.concat([df,separacion_lista['tipo']], axis = 1)
df

"""Vamos a dividir los títulos en sus diferentes niveles y generar así nuevas variables"""

separacion_cols = df.Title.str.split(pat = ':', expand=True)
separacion_cols

separacion_cols.columns = ['nivel1','nivel2','nivel3','nivel4','nivel5','nivel6','nivel7','nivel8']
separacion_cols

df = pd.concat([df,separacion_cols], axis = 1)
df

"""### 3.2 VARIABLES DERIVADAS DE LA FECHA

Podemos extraer los diferentes compontentes de una fecha para generar nuevas variables.
"""

df['fecha'] = pd.to_datetime(df.Date)
df.drop(columns = 'Date',inplace = True)
df

df.set_index('fecha', inplace = True)
df

"""Creamos una función para extraer los componentes."""

def atributos_fechas(data):
  data['año'] = data.index.year
  data['mes'] = data.index.month_name()
  data['dia_mes'] = data.index.day
  data['dia_semana'] = data.index.day_name()
  return(data)

atributos_fechas(df)

"""## 4. ANALISIS

¿Cuanto tiempo hace que tengo contratado Netflix?
"""

from datetime import date

hoy = pd.Timestamp(date.today())

primer_dia = df.index.min()

tiempo = hoy - primer_dia

print(f'Franca, llevas usando Netflix {tiempo.days} dias')

"""¿Cuanto me he gastado en Netflix hasta ahora?"""

# coste_mensual_2016 = 5190
# coste_mensual_2017_18 = 7390
# coste_mensual_2019_20 = 8.990
# coste_mensual_2021_22_23 = 10700
# media por mes = 8756.25

coste_mensual = 8756.25

gasto = tiempo.days / 30 * coste_mensual

print(f'Franca, hasta ahora has gastado {gasto} pesos en Netflix')

"""¿Cuanto tiempo de mi vida le dedico cada año a Netflix?"""

media_min_serie = 45
media_min_peli = 100

consumo = df.loc[df.año < 2024].groupby('tipo').Title.count()

minutos_pelis_año = consumo['pelicula'] * media_min_peli / 3

minutos_series_año = consumo['serie'] * media_min_serie / 3

dias_pelis_año = minutos_pelis_año / 60 / 24

dias_series_año = minutos_series_año / 60 / 24

print(f'Franca, al año dedicas {round(dias_series_año)} dias de tu vida a ver series y {round(dias_pelis_año)} dias de tu vida a ver pelis')

"""¿Cuales son las 10 series de las que he visto más capítulos?"""

df.loc[df.tipo == 'serie'].nivel1.value_counts(ascending = True).tail(10).plot.barh(cmap = 'Pastel1');

"""Vamos a hacer una consulta de los títulos que incluyan Pinocho en Title.

"""

df[df.Title.str.contains('Pinocho')]

"""¿Qué día de la semana suelo ver más series?"""

df.loc[df.tipo == 'serie', 'dia_semana'].value_counts().plot(kind = 'bar');

"""¿Existen diferencias en cuando veo Netflix entre series y películas?"""

import seaborn as sns

sns.countplot(data = df, x = 'dia_semana', hue = 'tipo', palette= 'pastel');

"""¿El consumo a lo largo del año es constante o hay meses que consumo más?"""

df.loc[df.año < 2024].mes.value_counts().plot.bar();

"""¿Afectó el confinamiento a la cantidad de uso que hice de Netflix?"""

df.año.value_counts().plot.bar();